apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: petclinic
  name: petclinic
  selfLink: /api/v1/namespaces/default/services/petclinic
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31998
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: petclinic
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
